const questions=[
 {c:'Intereses',q:'¿Qué actividad te gustaría realizar más?',a:[['Resolver problemas con computadoras','tecnologia'],['Crear diseños o contenidos','creatividad'],['Ayudar y orientar a otras personas','social'],['Organizar proyectos y tomar decisiones','negocios']]},
 {c:'Habilidades',q:'¿Qué se te hace más fácil?',a:[['Analizar información y encontrar soluciones','tecnologia'],['Expresar ideas de forma creativa','creatividad'],['Escuchar y comprender a otros','social'],['Planificar y organizar tareas','negocios']]},
 {c:'Preferencias',q:'En un proyecto escolar prefieres...',a:[['Encargarte de la parte tecnológica','tecnologia'],['Hacer la presentación y diseño','creatividad'],['Coordinar con el equipo y apoyar a los demás','social'],['Dirigir y repartir responsabilidades','negocios']]},
 {c:'Intereses',q:'¿Qué tema te llama más la atención?',a:[['Tecnología e innovación','tecnologia'],['Arte, comunicación y diseño','creatividad'],['Psicología, educación o salud','social'],['Empresas, economía y liderazgo','negocios']]},
 {c:'Habilidades',q:'Cuando aparece un problema, normalmente...',a:[['Buscas cómo funciona para solucionarlo','tecnologia'],['Piensas en una solución diferente','creatividad'],['Preguntas y escuchas a quienes están involucrados','social'],['Organizas los pasos para resolverlo','negocios']]},
 {c:'Preferencias',q:'¿Qué ambiente de trabajo te atrae?',a:[['Computadoras, laboratorios o proyectos tecnológicos','tecnologia'],['Espacios creativos y dinámicos','creatividad'],['Trabajo con personas y equipos','social'],['Reuniones, proyectos y coordinación','negocios']]},
 {c:'Intereses',q:'¿Cuál de estas actividades elegirías?',a:[['Programar o aprender una herramienta digital','tecnologia'],['Editar imágenes o videos','creatividad'],['Participar en una actividad de apoyo social','social'],['Crear una idea para un pequeño negocio','negocios']]},
 {c:'Habilidades',q:'¿Cómo aprendes mejor?',a:[['Probando y experimentando','tecnologia'],['Creando ejemplos y proyectos visuales','creatividad'],['Conversando y trabajando con otros','social'],['Organizando la información en planes','negocios']]},
 {c:'Preferencias',q:'¿Qué logro te haría sentir orgulloso/a?',a:[['Crear una solución tecnológica útil','tecnologia'],['Crear algo original que destaque','creatividad'],['Ayudar a alguien a mejorar','social'],['Liderar un proyecto exitoso','negocios']]},
 {c:'Intereses',q:'¿Qué curso te resulta más interesante?',a:[['Computación o ciencia','tecnologia'],['Arte o comunicación','creatividad'],['Ciencias sociales o educación','social'],['Economía o gestión','negocios']]},
 {c:'Habilidades',q:'En un equipo sueles ser quien...',a:[['Soluciona problemas técnicos','tecnologia'],['Propone ideas nuevas','creatividad'],['Mantiene unido al grupo','social'],['Organiza el trabajo','negocios']]},
 {c:'Preferencias',q:'¿Qué proyecto escogerías?',a:[['Crear una página web sencilla','tecnologia'],['Diseñar una campaña visual','creatividad'],['Crear una campaña de ayuda a estudiantes','social'],['Diseñar un pequeño plan de negocio','negocios']]},
 {c:'Intereses',q:'¿Qué te gustaría aprender?',a:[['Programación y tecnología','tecnologia'],['Diseño y producción audiovisual','creatividad'],['Comunicación y orientación','social'],['Administración y emprendimiento','negocios']]},
 {c:'Habilidades',q:'¿Qué característica te identifica más?',a:[['Soy curioso/a para entender cómo funcionan las cosas','tecnologia'],['Tengo imaginación para crear','creatividad'],['Me preocupo por los demás','social'],['Me gusta organizar y dirigir','negocios']]},
 {c:'Preferencias',q:'Si tuvieras que presentar un proyecto, preferirías...',a:[['Mostrar cómo funciona una solución','tecnologia'],['Encargarme de la parte visual','creatividad'],['Explicar cómo beneficia a las personas','social'],['Presentar el plan y los objetivos','negocios']]},
 {c:'Intereses',q:'¿Qué tipo de contenido consumes con mayor interés?',a:[['Tecnología y novedades digitales','tecnologia'],['Diseño, música o videos','creatividad'],['Historias y temas humanos','social'],['Emprendimiento y negocios','negocios']]},
 {c:'Habilidades',q:'Cuando trabajas bajo presión...',a:[['Analizas el problema y buscas una solución','tecnologia'],['Improvisas ideas para avanzar','creatividad'],['Buscas mantener una buena comunicación','social'],['Priorizas tareas y tiempos','negocios']]},
 {c:'Preferencias',q:'¿Qué tipo de resultado te gustaría obtener de tu trabajo?',a:[['Un sistema o herramienta que funcione','tecnologia'],['Una creación que comunique una idea','creatividad'],['Un cambio positivo en las personas','social'],['Un proyecto que alcance sus objetivos','negocios']]},
 {c:'Intereses',q:'¿Qué profesión te genera curiosidad?',a:[['Ingeniería de Sistemas o Informática','tecnologia'],['Diseño, publicidad o comunicación','creatividad'],['Psicología, educación o enfermería','social'],['Administración, economía o marketing','negocios']]},
 {c:'Habilidades',q:'¿Qué haces cuando no sabes cómo hacer algo?',a:[['Investigo cómo funciona','tecnologia'],['Pruebo diferentes formas','creatividad'],['Pido orientación a alguien','social'],['Organizo un plan para aprenderlo','negocios']]},
 {c:'Preferencias',q:'¿Qué te gustaría aportar a la sociedad?',a:[['Innovación y soluciones tecnológicas','tecnologia'],['Nuevas ideas y expresiones creativas','creatividad'],['Bienestar y apoyo a las personas','social'],['Emprendimiento y desarrollo económico','negocios']]},
 {c:'Intereses',q:'¿Qué reto elegirías?',a:[['Construir una aplicación sencilla','tecnologia'],['Crear la identidad visual de un proyecto','creatividad'],['Organizar una actividad para ayudar a estudiantes','social'],['Dirigir un proyecto desde su planificación','negocios']]},
 {c:'Habilidades',q:'¿Qué comentario te representa mejor?',a:[['“Me gusta descubrir cómo funcionan las cosas.”','tecnologia'],['“Siempre tengo ideas para crear algo.”','creatividad'],['“Las personas pueden confiar en mí.”','social'],['“Me gusta que las cosas estén organizadas.”','negocios']]},
 {c:'Preferencias',q:'¿Qué te motivaría más en una carrera?',a:[['Aprender y aplicar nuevas tecnologías','tecnologia'],['Crear y comunicar ideas','creatividad'],['Trabajar para mejorar la vida de otros','social'],['Liderar proyectos y tomar decisiones','negocios']]},
 {c:'Intereses',q:'Si pudieras hacer una pasantía, elegirías...',a:[['Una empresa tecnológica','tecnologia'],['Una agencia creativa o de medios','creatividad'],['Una institución educativa o social','social'],['Una empresa o emprendimiento','negocios']]}
];
let current=0;let answers=[];let user={};let scores={tecnologia:0,creatividad:0,social:0,negocios:0};
const labels={tecnologia:'Tecnología e ingeniería',creatividad:'Creatividad y comunicación',social:'Ciencias sociales y ayuda',negocios:'Negocios y gestión'};
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function goToRegister(){showScreen('register');}
document.getElementById('userForm').addEventListener('submit',e=>{e.preventDefault();user={name:document.getElementById('name').value.trim(),age:document.getElementById('age').value,grade:document.getElementById('grade').value};localStorage.setItem('pmvUser',JSON.stringify(user));current=0;answers=[];scores={tecnologia:0,creatividad:0,social:0,negocios:0};showScreen('test');renderQuestion();});
function renderQuestion(){const item=questions[current];document.getElementById('questionCounter').textContent=`Pregunta ${current+1} de ${questions.length}`;const pct=Math.round(((current+1)/questions.length)*100);document.getElementById('progressPercent').textContent=`${pct}%`;document.getElementById('progressBar').style.width=`${pct}%`;document.getElementById('categoryLabel').textContent=item.c;document.getElementById('questionText').textContent=item.q;const box=document.getElementById('answers');box.innerHTML='';item.a.forEach(([text,value])=>{const b=document.createElement('button');b.className='answer';b.textContent=text;b.onclick=()=>selectAnswer(b,value);box.appendChild(b);});document.getElementById('nextBtn').disabled=true;}
function selectAnswer(button,value){document.querySelectorAll('.answer').forEach(b=>b.classList.remove('selected'));button.classList.add('selected');answers[current]=value;document.getElementById('nextBtn').disabled=false;}
document.getElementById('nextBtn').addEventListener('click',()=>{if(!answers[current])return;if(current<questions.length-1){current++;renderQuestion();}else finishTest();});
function finishTest(){scores={tecnologia:0,creatividad:0,social:0,negocios:0};answers.forEach(a=>scores[a]++);const sorted=Object.entries(scores).sort((a,b)=>b[1]-a[1]);const max=sorted[0][1];document.getElementById('resultGreeting').textContent=`¡Buen trabajo, ${user.name || 'estudiante'}!`;document.getElementById('resultList').innerHTML=sorted.map(([key,value])=>{const pct=Math.round((value/max)*100);return `<div class="result-item"><div class="row"><span>${labels[key]}</span><span>${value}/${questions.length}</span></div><div class="result-bar"><span style="width:${pct}%"></span></div></div>`}).join('');localStorage.setItem('pmvResult',JSON.stringify({user,scores}));showScreen('results');}
function restartTest(){current=0;answers=[];scores={tecnologia:0,creatividad:0,social:0,negocios:0};showScreen('test');renderQuestion();}
